import re
from typing import List, Dict, Any

class MinimalSolutionRegistry:
    def __init__(self):
        self._solutions = {}
        self._search_index = {} # token -> set of identifies

    def _tokenize(self, text: str) -> set:
        if not text:
            return set()
        return set(re.findall(r'\w+', str(text).lower()))

    def _build_index(self, identify: str, solution: dict):
        search_parts = [
            solution.get('title', ''),
            solution.get('description', ''),
            solution.get('category', ''),
            ' '.join(solution.get('tags', []))
        ]
        text_data = ' '.join(filter(None, search_parts))
        tokens = self._tokenize(text_data)
        for token in tokens:
            if token not in self._search_index:
                self._search_index[token] = set()
            self._search_index[token].add(identify)

    def register(self, identify, title, category, description="", tags=None, folder=None, ui_route=None, api_endpoint=None, status="Active", **kwargs):
        if identify in self._solutions:
            raise ValueError(f"Solution with identify '{identify}' is already registered.")
        
        if tags is None:
            tags = []
            
        if not folder:
            folder = f"minimal_solutions/{identify}"
        if not ui_route:
            ui_route = f"/minimal-solutions/{identify}"
        if not api_endpoint:
            api_endpoint = f"/api/minimal-solutions/{identify}"

        solution = {
            "identify": identify,
            "title": title,
            "category": category,
            "description": description,
            "tags": tags,
            "folder": folder,
            "ui_route": ui_route,
            "api_endpoint": api_endpoint,
            "status": status
        }
        solution.update(kwargs)
        self._solutions[identify] = solution
        self._build_index(identify, solution)
        return solution

    def get_all(self):
        return list(self._solutions.values())

    def get(self, identify):
        return self._solutions.get(identify)

    def search(self, query: str) -> List[Dict[str, Any]]:
        if not query:
            return self.get_all()
            
        query_tokens = self._tokenize(query)
        if not query_tokens:
            return self.get_all()
            
        scores = {}
        for q_token in query_tokens:
            for indexed_token, identifies in self._search_index.items():
                score = 0
                if q_token == indexed_token:
                    score = 10
                elif q_token in indexed_token:
                    score = 3
                elif indexed_token in q_token and len(indexed_token) > 2:
                    score = 1
                    
                if score > 0:
                    for identify in identifies:
                        scores[identify] = scores.get(identify, 0) + score
                        
        query_lower = query.lower()
        for identify, sol in self._solutions.items():
            if query_lower in sol['title'].lower():
                scores[identify] = scores.get(identify, 0) + 15
            elif query_lower in sol.get('description', '').lower():
                scores[identify] = scores.get(identify, 0) + 5
                
        sorted_identifies = sorted(scores.items(), key=lambda x: x[1], reverse=True)
        return [self._solutions[ident] for ident, score in sorted_identifies]

registry = MinimalSolutionRegistry()

# Register some initial or placeholder solutions if necessary
registry.register('json_formatter', 'JSON Formatter', 'developer', description='Format and validate JSON objects.', tags=['json', 'format', 'validate'], folder='minimal_solutions/json_formatter', ui_route='/minimal-solutions/json_formatter', api_endpoint='/api/minimal-solutions/json_formatter', status='Active')
registry.register('base64_encoder_decoder', 'Base64 Encoder Decoder', 'developer', description='Encode and decode base64 strings.', tags=['base64', 'encode', 'decode'], folder='minimal_solutions/base64_encoder_decoder', ui_route='/minimal-solutions/base64_encoder_decoder', api_endpoint='/api/minimal-solutions/base64_encoder_decoder', status='Active')
registry.register('uuid_generator', 'UUID Generator', 'developer', description='Generate random UUIDs.', tags=['uuid', 'generator', 'random'], folder='minimal_solutions/uuid_generator', ui_route='/minimal-solutions/uuid_generator', api_endpoint='/api/minimal-solutions/uuid_generator', status='Active', request_example='{\n  "count": 3,\n  "version": 4\n}', response_example='{\n  "status": "success",\n  "data": {\n    "uuids": [\n      "e4ea61d1-671c-4b61-9c60-a241eb405786",\n      "2b7e1516-28aec-4660-8f9d-11445b23d932",\n      "a30f14d9-81a1-4357-bb03-68f760db1e9f"\n    ],\n    "count": 3,\n    "version": 4\n  }\n}')
registry.register('markdown_preview', 'Markdown Preview', 'content', description='Live preview for Markdown text.', tags=['markdown', 'preview', 'editor'], folder='minimal_solutions/markdown_preview', ui_route='/minimal-solutions/markdown_preview', api_endpoint='/api/minimal-solutions/markdown_preview', status='Active')
registry.register('qr_code_generator', 'QR-Code Generator', 'utility', description='Generate QR codes from text or URLs.', tags=['qr', 'qrcode', 'generator', 'utility'], folder='minimal_solutions/qr_code_generator', ui_route='/minimal-solutions/qr_code_generator', api_endpoint='/api/minimal-solutions/qr_code_generator', status='Active', request_example='{\n  "type": "url",\n  "url": "https://example.com"\n}', response_example='{\n  "status": "success",\n  "data": {\n    "type": "url",\n    "format": "png",\n    "size": 512,\n    "url": "data:image/png;base64,iVBORw0KGgo..."\n  }\n}')
registry.register('passwort_generator', 'Passwort Generator', 'security', description='Generate secure random passwords.', tags=['password', 'generator', 'security'], folder='minimal_solutions/passwort_generator', ui_route='/minimal-solutions/passwort_generator', api_endpoint='/api/minimal-solutions/passwort_generator', status='Active', request_example='{\n  "length": 16,\n  "use_uppercase": true,\n  "use_numbers": true,\n  "use_symbols": true\n}', response_example='{\n  "status": "success",\n  "data": {\n    "password": "aB3$eX9@lP2#kR7!",\n    "length": 16,\n    "strength": "strong"\n  }\n}')
registry.register('json_minifier', 'JSON Minifier', 'developer', description='Minify and compress JSON objects.', tags=['json', 'minify', 'compress', 'developer'], folder='minimal_solutions/json_minifier', ui_route='/minimal-solutions/json_minifier', api_endpoint='/api/minimal-solutions/json_minifier', status='Active')
registry.register('url_encoder_decoder', 'URL Encoder Decoder', 'developer', description='Encode and decode URL parameters and strings.', tags=['url', 'encode', 'decode', 'developer'], folder='minimal_solutions/url_encoder_decoder', ui_route='/minimal-solutions/url_encoder_decoder', api_endpoint='/api/minimal-solutions/url_encoder_decoder', status='Active')
registry.register('hash_generator', 'Hash Generator', 'security', description='Generate hashes from text.', tags=['hash', 'generator', 'security'], folder='minimal_solutions/hash_generator', ui_route='/minimal-solutions/hash_generator', api_endpoint='/api/minimal-solutions/hash_generator', status='Active')
registry.register('timestamp_converter', 'Timestamp Converter', 'developer', description='Convert timestamps to dates and vice versa.', tags=['timestamp', 'time', 'date', 'converter', 'developer'], folder='minimal_solutions/timestamp_converter', ui_route='/minimal-solutions/timestamp_converter', api_endpoint='/api/minimal-solutions/timestamp_converter', status='Active')
registry.register('farbkonverter', 'Farbkonverter', 'design', description='Convert between color formats (HEX, RGB, HSL).', tags=['color', 'converter', 'hex', 'rgb', 'hsl', 'design'], folder='minimal_solutions/farbkonverter', ui_route='/minimal-solutions/farbkonverter', api_endpoint='/api/minimal-solutions/farbkonverter', status='Active', request_example='{\n  "color_value": "#FF5733"\n}', response_example='{\n  "status": "success",\n  "data": {\n    "hex": "#FF5733",\n    "rgb": "rgb(255, 87, 51)",\n    "rgba": "rgba(255, 87, 51, 1)",\n    "hsl": "hsl(11, 100%, 60%)"\n  }\n}')
registry.register('css_gradient_generator', 'CSS Gradient Generator', 'design', description='Generate and customize CSS gradients.', tags=['css', 'gradient', 'generator', 'design', 'ui'], folder='minimal_solutions/css_gradient_generator', ui_route='/minimal-solutions/css_gradient_generator', api_endpoint='/api/minimal-solutions/css_gradient_generator', status='Active')
registry.register('box_shadow_generator', 'Box Shadow Generator', 'design', description='Generate and customize CSS box shadows.', tags=['css', 'shadow', 'generator', 'design', 'ui'], folder='minimal_solutions/box_shadow_generator', ui_route='/minimal-solutions/box_shadow_generator', api_endpoint='/api/minimal-solutions/box_shadow_generator', status='Active')
registry.register('border_radius_generator', 'Border Radius Generator', 'design', description='Generate and customize CSS border radius.', tags=['css', 'border', 'radius', 'generator', 'design', 'ui'], folder='minimal_solutions/border_radius_generator', ui_route='/minimal-solutions/border_radius_generator', api_endpoint='/api/minimal-solutions/border_radius_generator', status='Active')
registry.register('meta_tag_generator', 'Meta Tag Generator', 'seo', description='Generate HTML meta tags for SEO and social media.', tags=['meta', 'tags', 'seo', 'generator', 'html'], folder='minimal_solutions/meta_tag_generator', ui_route='/minimal-solutions/meta_tag_generator', api_endpoint='/api/minimal-solutions/meta_tag_generator', status='Active')
registry.register('robots_txt_generator', 'Robots TXT Generator', 'seo', description='Generate robots.txt files for SEO.', tags=['robots', 'txt', 'seo', 'generator'], folder='minimal_solutions/robots_txt_generator', ui_route='/minimal-solutions/robots_txt_generator', api_endpoint='/api/minimal-solutions/robots_txt_generator', status='Active')
registry.register('sitemap_xml_generator', 'Sitemap XML Generator', 'seo', description='Generate sitemap.xml files for SEO.', tags=['sitemap', 'xml', 'seo', 'generator'], folder='minimal_solutions/sitemap_xml_generator', ui_route='/minimal-solutions/sitemap_xml_generator', api_endpoint='/api/minimal-solutions/sitemap_xml_generator', status='Active')
registry.register('opengraph_preview', 'OpenGraph Preview', 'seo', description='Preview OpenGraph tags for a given URL.', tags=['opengraph', 'preview', 'seo'], folder='minimal_solutions/opengraph_preview', ui_route='/minimal-solutions/opengraph_preview', api_endpoint='/api/minimal-solutions/opengraph_preview', status='Active')
registry.register('link_shortener_demo', 'Link Shortener Demo', 'marketing', description='Demo for a link shortener service.', tags=['link', 'shortener', 'demo', 'marketing'], folder='minimal_solutions/link_shortener_demo', ui_route='/minimal-solutions/link_shortener_demo', api_endpoint='/api/minimal-solutions/link_shortener_demo', status='Active')
registry.register('utm_link_builder', 'UTM Link Builder', 'marketing', description='Build URLs with UTM parameters for campaign tracking.', tags=['utm', 'link', 'builder', 'marketing', 'tracking'], folder='minimal_solutions/utm_link_builder', ui_route='/minimal-solutions/utm_link_builder', api_endpoint='/api/minimal-solutions/utm_link_builder', status='Active')
registry.register('cta_generator', 'CTA Generator', 'marketing', description='Generate Call-to-Action buttons and links.', tags=['cta', 'generator', 'marketing', 'button'], folder='minimal_solutions/cta_generator', ui_route='/minimal-solutions/cta_generator', api_endpoint='/api/minimal-solutions/cta_generator', status='Active')
registry.register('headline_generator', 'Headline Generator', 'marketing', description='Generate catchy headlines for your content.', tags=['headline', 'generator', 'marketing', 'copywriting'], folder='minimal_solutions/headline_generator', ui_route='/minimal-solutions/headline_generator', api_endpoint='/api/minimal-solutions/headline_generator', status='Active', request_example='{\n  "topic": "Artificial Intelligence",\n  "style": "clickbait",\n  "count": 3\n}', response_example='{\n  "status": "success",\n  "data": {\n    "headlines": [\n      "The Secret to Artificial Intelligence That Will Change Your Life",\n      "10 Mind-Blowing Facts About Artificial Intelligence",\n      "Why Artificial Intelligence is the Future"\n    ]\n  }\n}')
registry.register('e_mail_betreff_generator', 'E-Mail Betreff Generator', 'marketing', description='Generate catchy email subject lines.', tags=['email', 'subject', 'generator', 'marketing', 'copywriting'], folder='minimal_solutions/e_mail_betreff_generator', ui_route='/minimal-solutions/e_mail_betreff_generator', api_endpoint='/api/minimal-solutions/e_mail_betreff_generator', status='Active')
registry.register('impressum_generator_demo', 'Impressum Generator Demo', 'business', description='Demo for generating an Impressum.', tags=['impressum', 'generator', 'demo', 'business', 'legal'], folder='minimal_solutions/impressum_generator_demo', ui_route='/minimal-solutions/impressum_generator_demo', api_endpoint='/api/minimal-solutions/impressum_generator_demo', status='Active')
registry.register('datenschutz_text_demo', 'Datenschutz Text Demo', 'business', description='Demo for a Datenschutz text generator.', tags=['datenschutz', 'text', 'demo', 'business', 'legal'], folder='minimal_solutions/datenschutz_text_demo', ui_route='/minimal-solutions/datenschutz_text_demo', api_endpoint='/api/minimal-solutions/datenschutz_text_demo', status='Active')
registry.register('rechnungsnummer_generator', 'Rechnungsnummer Generator', 'business', description='Generate structured invoice numbers.', tags=['invoice', 'number', 'generator', 'business', 'billing'], folder='minimal_solutions/rechnungsnummer_generator', ui_route='/minimal-solutions/rechnungsnummer_generator', api_endpoint='/api/minimal-solutions/rechnungsnummer_generator', status='Active')
registry.register('angebotsnummer_generator', 'Angebotsnummer Generator', 'business', description='Generate structured offer numbers.', tags=['offer', 'number', 'generator', 'business', 'sales'], folder='minimal_solutions/angebotsnummer_generator', ui_route='/minimal-solutions/angebotsnummer_generator', api_endpoint='/api/minimal-solutions/angebotsnummer_generator', status='Active')
registry.register('iban_formatter', 'IBAN Formatter', 'finance', description='Format and validate IBAN numbers.', tags=['iban', 'formatter', 'finance', 'validation'], folder='minimal_solutions/iban_formatter', ui_route='/minimal-solutions/iban_formatter', api_endpoint='/api/minimal-solutions/iban_formatter', status='Active')
registry.register('mwst_rechner', 'MwSt Rechner', 'finance', description='Calculate VAT (Mehrwertsteuer) amounts.', tags=['mwst', 'vat', 'tax', 'finance', 'calculator'], folder='minimal_solutions/mwst_rechner', ui_route='/minimal-solutions/mwst_rechner', api_endpoint='/api/minimal-solutions/mwst_rechner', status='Active')
registry.register('preis_kalkulator', 'Preis Kalkulator', 'finance', description='Calculate prices, margins and discounts.', tags=['price', 'calculator', 'finance', 'margin', 'discount'], folder='minimal_solutions/preis_kalkulator', ui_route='/minimal-solutions/preis_kalkulator', api_endpoint='/api/minimal-solutions/preis_kalkulator', status='Active')
registry.register('csv_zu_json_converter', 'CSV zu JSON Converter', 'data', description='Convert CSV data to JSON format.', tags=['csv', 'json', 'converter', 'data'], folder='minimal_solutions/csv_zu_json_converter', ui_route='/minimal-solutions/csv_zu_json_converter', api_endpoint='/api/minimal-solutions/csv_zu_json_converter', status='Active')
registry.register('json_zu_csv_converter', 'JSON zu CSV Converter', 'data', description='Convert JSON data to CSV format.', tags=['json', 'csv', 'converter', 'data'], folder='minimal_solutions/json_zu_csv_converter', ui_route='/minimal-solutions/json_zu_csv_converter', api_endpoint='/api/minimal-solutions/json_zu_csv_converter', status='Active')
registry.register('html_escape_unescape', 'HTML Escape Unescape', 'developer', description='Escape and unescape HTML entities.', tags=['html', 'escape', 'unescape', 'developer'], folder='minimal_solutions/html_escape_unescape', ui_route='/minimal-solutions/html_escape_unescape', api_endpoint='/api/minimal-solutions/html_escape_unescape', status='Active')
registry.register('regex_tester', 'Regex Tester', 'developer', description='Test and validate regular expressions.', tags=['regex', 'tester', 'regular expression', 'developer'], folder='minimal_solutions/regex_tester', ui_route='/minimal-solutions/regex_tester', api_endpoint='/api/minimal-solutions/regex_tester', status='Active')
registry.register('cron_expression_helper', 'Cron Expression Helper', 'developer', description='Generate and translate cron expressions.', tags=['cron', 'expression', 'helper', 'scheduler', 'developer'], folder='minimal_solutions/cron_expression_helper', ui_route='/minimal-solutions/cron_expression_helper', api_endpoint='/api/minimal-solutions/cron_expression_helper', status='Active')
registry.register('http_status_lookup', 'HTTP Status Lookup', 'developer', description='Lookup and explain HTTP status codes.', tags=['http', 'status', 'lookup', 'developer'], folder='minimal_solutions/http_status_lookup', ui_route='/minimal-solutions/http_status_lookup', api_endpoint='/api/minimal-solutions/http_status_lookup', status='Active')
registry.register('mime_type_lookup', 'MIME Type Lookup', 'developer', description='Lookup and identify MIME types from extensions.', tags=['mime', 'type', 'lookup', 'developer', 'extension'], folder='minimal_solutions/mime_type_lookup', ui_route='/minimal-solutions/mime_type_lookup', api_endpoint='/api/minimal-solutions/mime_type_lookup', status='Active')
registry.register('jwt_decoder_demo', 'JWT Decoder Demo', 'security', description='Decode and inspect JSON Web Tokens.', tags=['jwt', 'decoder', 'demo', 'security'], folder='minimal_solutions/jwt_decoder_demo', ui_route='/minimal-solutions/jwt_decoder_demo', api_endpoint='/api/minimal-solutions/jwt_decoder_demo', status='Active')
registry.register('random_name_generator', 'Random Name Generator', 'utility', description='Generate random names.', tags=['random', 'name', 'generator', 'utility'], folder='minimal_solutions/random_name_generator', ui_route='/minimal-solutions/random_name_generator', api_endpoint='/api/minimal-solutions/random_name_generator', status='Active', request_example='{\n  "category": "project",\n  "count": 3\n}', response_example='{\n  "status": "success",\n  "data": {\n    "names": [\n      "NexusCore",\n      "QuantumSync",\n      "AeroShift"\n    ]\n  }\n}')
registry.register('lorem_ipsum_generator', 'Lorem Ipsum Generator', 'content', description='Generate placeholder text.', tags=['lorem', 'ipsum', 'generator', 'content', 'placeholder'], folder='minimal_solutions/lorem_ipsum_generator', ui_route='/minimal-solutions/lorem_ipsum_generator', api_endpoint='/api/minimal-solutions/lorem_ipsum_generator', status='Active')
registry.register('word_replacer', 'Word Replacer', 'content', description='Replace specific words or phrases in a given text.', tags=['word', 'replacer', 'text', 'content', 'replace'], folder='minimal_solutions/word_replacer', ui_route='/minimal-solutions/word_replacer', api_endpoint='/api/minimal-solutions/word_replacer', status='Active')
registry.register('case_converter', 'Case Converter', 'content', description='Convert text between different letter cases.', tags=['case', 'converter', 'text', 'content'], folder='minimal_solutions/case_converter', ui_route='/minimal-solutions/case_converter', api_endpoint='/api/minimal-solutions/case_converter', status='Active')
registry.register('lesezeit_rechner', 'Lesezeit Rechner', 'content', description='Calculate estimated reading time for a given text.', tags=['lesezeit', 'rechner', 'reading', 'time', 'content'], folder='minimal_solutions/lesezeit_rechner', ui_route='/minimal-solutions/lesezeit_rechner', api_endpoint='/api/minimal-solutions/lesezeit_rechner', status='Active')
registry.register('dateigroessen_converter', 'Dateigrößen Converter', 'utility', description='Convert file sizes between different units (Bytes, KB, MB, GB, etc.).', tags=['file', 'size', 'converter', 'utility'], folder='minimal_solutions/dateigroessen_converter', ui_route='/minimal-solutions/dateigroessen_converter', api_endpoint='/api/minimal-solutions/dateigroessen_converter', status='Active')
registry.register('einheiten_converter', 'Einheiten Converter', 'utility', description='Convert between different units of measurement.', tags=['unit', 'converter', 'utility'], folder='minimal_solutions/einheiten_converter', ui_route='/minimal-solutions/einheiten_converter', api_endpoint='/api/minimal-solutions/einheiten_converter', status='Active')
registry.register('altersrechner', 'Altersrechner', 'utility', description='Calculate exact age from date of birth.', tags=['age', 'calculator', 'date', 'utility'], folder='minimal_solutions/altersrechner', ui_route='/minimal-solutions/altersrechner', api_endpoint='/api/minimal-solutions/altersrechner', status='Active')
registry.register('datumsdifferenz_rechner', 'Datumsdifferenz Rechner', 'utility', description='Calculate the difference between two dates.', tags=['date', 'difference', 'calculator', 'utility'], folder='minimal_solutions/datumsdifferenz_rechner', ui_route='/minimal-solutions/datumsdifferenz_rechner', api_endpoint='/api/minimal-solutions/datumsdifferenz_rechner', status='Active')
registry.register('countdown_generator', 'Countdown Generator', 'marketing', description='Generate countdown timers for events.', tags=['countdown', 'timer', 'marketing'], folder='minimal_solutions/countdown_generator', ui_route='/minimal-solutions/countdown_generator', api_endpoint='/api/minimal-solutions/countdown_generator', status='Active')
registry.register('kontaktkarten_generator', 'Kontaktkarten Generator', 'business', description='Generate digital contact cards.', tags=['contact', 'card', 'generator', 'business', 'vcard'], folder='minimal_solutions/kontaktkarten_generator', ui_route='/minimal-solutions/kontaktkarten_generator', api_endpoint='/api/minimal-solutions/kontaktkarten_generator', status='Active')
registry.register('vcard_generator', 'vCard Generator', 'business', description='Generate and download vCard files.', tags=['vcard', 'contact', 'generator', 'business'], folder='minimal_solutions/vcard_generator', ui_route='/minimal-solutions/vcard_generator', api_endpoint='/api/minimal-solutions/vcard_generator', status='Active')
registry.register('e_mail_signatur_generator', 'E-Mail Signatur Generator', 'business', description='Generate professional email signatures.', tags=['email', 'signature', 'generator', 'business'], folder='minimal_solutions/e_mail_signatur_generator', ui_route='/minimal-solutions/e_mail_signatur_generator', api_endpoint='/api/minimal-solutions/e_mail_signatur_generator', status='Active')
registry.register('favicon_generator_demo', 'Favicon Generator Demo', 'design', description='Generate and preview favicons for your website.', tags=['favicon', 'generator', 'design', 'demo'], folder='minimal_solutions/favicon_generator_demo', ui_route='/minimal-solutions/favicon_generator_demo', api_endpoint='/api/minimal-solutions/favicon_generator_demo', status='Active')
registry.register('svg_icon_generator', 'SVG Icon Generator', 'design', description='Generate and customize SVG icons.', tags=['svg', 'icon', 'generator', 'design'], folder='minimal_solutions/svg_icon_generator', ui_route='/minimal-solutions/svg_icon_generator', api_endpoint='/api/minimal-solutions/svg_icon_generator', status='Active')
registry.register('badge_generator', 'Badge Generator', 'design', description='Generate custom badges for projects.', tags=['badge', 'generator', 'design'], folder='minimal_solutions/badge_generator', ui_route='/minimal-solutions/badge_generator', api_endpoint='/api/minimal-solutions/badge_generator', status='Active')
registry.register('changelog_generator', 'Changelog Generator', 'developer', description='Generate structured project changelogs.', tags=['changelog', 'generator', 'developer', 'release'], folder='minimal_solutions/changelog_generator', ui_route='/minimal-solutions/changelog_generator', api_endpoint='/api/minimal-solutions/changelog_generator', status='Active')
registry.register('release_notes_generator', 'Release Notes Generator', 'developer', description='Generate structured release notes for your projects.', tags=['release', 'notes', 'generator', 'developer'], folder='minimal_solutions/release_notes_generator', ui_route='/minimal-solutions/release_notes_generator', api_endpoint='/api/minimal-solutions/release_notes_generator', status='Active')
registry.register('api_key_masker', 'API Key Masker', 'security', description='Mask and format API keys for secure display.', tags=['api', 'key', 'masker', 'security'], folder='minimal_solutions/api_key_masker', ui_route='/minimal-solutions/api_key_masker', api_endpoint='/api/minimal-solutions/api_key_masker', status='Active')
registry.register('env_file_viewer', 'ENV File Viewer', 'developer', description='View and analyze .env files securely.', tags=['env', 'file', 'viewer', 'developer', 'environment'], folder='minimal_solutions/env_file_viewer', ui_route='/minimal-solutions/env_file_viewer', api_endpoint='/api/minimal-solutions/env_file_viewer', status='Active')
registry.register('docker_compose_service_viewer', 'Docker Compose Service Viewer', 'developer', description='View and analyze Docker Compose services.', tags=['docker', 'compose', 'service', 'viewer', 'developer'], folder='minimal_solutions/docker_compose_service_viewer', ui_route='/minimal-solutions/docker_compose_service_viewer', api_endpoint='/api/minimal-solutions/docker_compose_service_viewer', status='Active')
registry.register('port_checker_demo', 'Port Checker Demo', 'developer', description='Check if specific ports are open on a given host.', tags=['port', 'checker', 'demo', 'network', 'developer'], folder='minimal_solutions/port_checker_demo', ui_route='/minimal-solutions/port_checker_demo', api_endpoint='/api/minimal-solutions/port_checker_demo', status='Active')
registry.register('log_highlighter', 'Log Highlighter', 'developer', description='Highlight and format log files for better readability.', tags=['log', 'highlighter', 'developer', 'viewer'], folder='minimal_solutions/log_highlighter', ui_route='/minimal-solutions/log_highlighter', api_endpoint='/api/minimal-solutions/log_highlighter', status='Active')
registry.register('error_message_explainer', 'Error Message Explainer', 'developer', description='Explain complex error messages in plain text.', tags=['error', 'message', 'explainer', 'developer', 'debug'], folder='minimal_solutions/error_message_explainer', ui_route='/minimal-solutions/error_message_explainer', api_endpoint='/api/minimal-solutions/error_message_explainer', status='Active')
registry.register('support_ticket_summarizer', 'Support Ticket Summarizer', 'support', description='Summarize long and complex support tickets automatically.', tags=['support', 'ticket', 'summarizer'], folder='minimal_solutions/support_ticket_summarizer', ui_route='/minimal-solutions/support_ticket_summarizer', api_endpoint='/api/minimal-solutions/support_ticket_summarizer', status='Active')
registry.register('faq_generator', 'FAQ Generator', 'support', description='Generate FAQ sections easily.', tags=['faq', 'generator', 'support'], folder='minimal_solutions/faq_generator', ui_route='/minimal-solutions/faq_generator', api_endpoint='/api/minimal-solutions/faq_generator', status='Active')
registry.register('knowledge_base_card_generator', 'Knowledge Base Card Generator', 'support', description='Generate knowledge base cards for support articles.', tags=['knowledge', 'base', 'card', 'generator', 'support'], folder='minimal_solutions/knowledge_base_card_generator', ui_route='/minimal-solutions/knowledge_base_card_generator', api_endpoint='/api/minimal-solutions/knowledge_base_card_generator', status='Active')
registry.register('ticket_priority_classifier', 'Ticket Priority Classifier', 'support', description='Classify the priority of support tickets automatically.', tags=['ticket', 'priority', 'classifier', 'support'], folder='minimal_solutions/ticket_priority_classifier', ui_route='/minimal-solutions/ticket_priority_classifier', api_endpoint='/api/minimal-solutions/ticket_priority_classifier', status='Active')
registry.register('sla_rechner', 'SLA Rechner', 'support', description='Calculate SLA metrics and downtimes.', tags=['sla', 'rechner', 'calculator', 'support', 'uptime'], folder='minimal_solutions/sla_rechner', ui_route='/minimal-solutions/sla_rechner', api_endpoint='/api/minimal-solutions/sla_rechner', status='Active')
registry.register('website_health_check_demo', 'Website Health Check Demo', 'monitoring', description='Demo for a website health check service.', tags=['website', 'health', 'check', 'demo', 'monitoring'], folder='minimal_solutions/website_health_check_demo', ui_route='/minimal-solutions/website_health_check_demo', api_endpoint='/api/minimal-solutions/website_health_check_demo', status='Active')
registry.register('uptime_badge_generator', 'Uptime Badge Generator', 'monitoring', description='Generate uptime badges for your services.', tags=['uptime', 'badge', 'generator', 'monitoring'], folder='minimal_solutions/uptime_badge_generator', ui_route='/minimal-solutions/uptime_badge_generator', api_endpoint='/api/minimal-solutions/uptime_badge_generator', status='Active', request_example='{\n  "status": "up",\n  "uptime_percent": 99.99\n}', response_example='{\n  "status": "success",\n  "data": {\n    "svg": "<svg>...</svg>",\n    "markdown": "![Uptime Badge](...)"\n  }\n}')
registry.register('server_resource_card_demo', 'Server Resource Card Demo', 'monitoring', description='Demo for server resource monitoring cards.', tags=['server', 'resource', 'card', 'demo', 'monitoring'], folder='minimal_solutions/server_resource_card_demo', ui_route='/minimal-solutions/server_resource_card_demo', api_endpoint='/api/minimal-solutions/server_resource_card_demo', status='Active')
registry.register('docker_container_card_demo', 'Docker Container Card Demo', 'monitoring', description='Demo for docker container cards.', tags=['docker', 'container', 'card', 'demo', 'monitoring'], folder='minimal_solutions/docker_container_card_demo', ui_route='/minimal-solutions/docker_container_card_demo', api_endpoint='/api/minimal-solutions/docker_container_card_demo', status='Active')
registry.register('minecraft_server_status_demo', 'Minecraft Server Status Demo', 'gaming', description='Demo for Minecraft server status.', tags=['minecraft', 'server', 'status', 'demo', 'gaming'], folder='minimal_solutions/minecraft_server_status_demo', ui_route='/minimal-solutions/minecraft_server_status_demo', api_endpoint='/api/minimal-solutions/minecraft_server_status_demo', status='Active')
registry.register('minecraft_motd_preview', 'Minecraft MOTD Preview', 'gaming', description='Preview Minecraft MOTD.', tags=['minecraft', 'motd', 'preview', 'gaming'], folder='minimal_solutions/minecraft_motd_preview', ui_route='/minimal-solutions/minecraft_motd_preview', api_endpoint='/api/minimal-solutions/minecraft_motd_preview', status='Active')
registry.register('subdomain_generator', 'Subdomain Generator', 'hosting', description='Generate subdomains based on input.', tags=['subdomain', 'generator', 'hosting'], folder='minimal_solutions/subdomain_generator', ui_route='/minimal-solutions/subdomain_generator', api_endpoint='/api/minimal-solutions/subdomain_generator', status='Active')
registry.register('dns_record_builder', 'DNS Record Builder', 'hosting', description='Build and manage DNS records.', tags=['dns', 'record', 'builder', 'hosting'], folder='minimal_solutions/dns_record_builder', ui_route='/minimal-solutions/dns_record_builder', api_endpoint='/api/minimal-solutions/dns_record_builder', status='Active', request_example='{\n  "type": "A",\n  "name": "www",\n  "value": "192.168.1.1",\n  "ttl": 3600\n}', response_example='{\n  "status": "success",\n  "data": {\n    "record": "www 3600 IN A 192.168.1.1",\n    "type": "A",\n    "name": "www",\n    "value": "192.168.1.1",\n    "ttl": 3600\n  }\n}')
registry.register('ssl_expiry_checker_demo', 'SSL Expiry Checker Demo', 'hosting', description='Check SSL certificate expiry dates.', tags=['ssl', 'expiry', 'checker', 'demo', 'hosting'], folder='minimal_solutions/ssl_expiry_checker_demo', ui_route='/minimal-solutions/ssl_expiry_checker_demo', api_endpoint='/api/minimal-solutions/ssl_expiry_checker_demo', status='Active')
registry.register('backup_plan_generator', 'Backup Plan Generator', 'hosting', description='Generate a backup plan strategy.', tags=['backup', 'plan', 'generator', 'hosting'], folder='minimal_solutions/backup_plan_generator', ui_route='/minimal-solutions/backup_plan_generator', api_endpoint='/api/minimal-solutions/backup_plan_generator', status='Active')
registry.register('maintenance_page_generator', 'Maintenance Page Generator', 'hosting', description='Generate a maintenance page HTML.', tags=['maintenance', 'page', 'generator', 'hosting', 'html'], folder='minimal_solutions/maintenance_page_generator', ui_route='/minimal-solutions/maintenance_page_generator', api_endpoint='/api/minimal-solutions/maintenance_page_generator', status='Active')
registry.register('status_page_incident_generator', 'Status Page Incident Generator', 'hosting', description='Generate status page incident reports.', tags=['status', 'page', 'incident', 'generator', 'hosting'], folder='minimal_solutions/status_page_incident_generator', ui_route='/minimal-solutions/status_page_incident_generator', api_endpoint='/api/minimal-solutions/status_page_incident_generator', status='Active')
registry.register('webhook_payload_tester', 'Webhook Payload Tester', 'developer', description='Test and inspect webhook payloads.', tags=['webhook', 'payload', 'tester', 'developer'], folder='minimal_solutions/webhook_payload_tester', ui_route='/minimal-solutions/webhook_payload_tester', api_endpoint='/api/minimal-solutions/webhook_payload_tester', status='Active')
registry.register('api_request_builder', 'API Request Builder', 'developer', description='Build and test API requests.', tags=['api', 'request', 'builder', 'developer'], folder='minimal_solutions/api_request_builder', ui_route='/minimal-solutions/api_request_builder', api_endpoint='/api/minimal-solutions/api_request_builder', status='Active')
registry.register('curl_command_generator', 'cURL Command Generator', 'developer', description='Generate cURL commands from structured data.', tags=['curl', 'command', 'generator', 'developer'], folder='minimal_solutions/curl_command_generator', ui_route='/minimal-solutions/curl_command_generator', api_endpoint='/api/minimal-solutions/curl_command_generator', status='Active')
registry.register('openapi_endpoint_stub_generator', 'OpenAPI Endpoint Stub Generator', 'developer', description='Generate OpenAPI endpoint stubs.', tags=['openapi', 'endpoint', 'stub', 'generator', 'developer'], folder='minimal_solutions/openapi_endpoint_stub_generator', ui_route='/minimal-solutions/openapi_endpoint_stub_generator', api_endpoint='/api/minimal-solutions/openapi_endpoint_stub_generator', status='Active')
registry.register('form_schema_generator', 'Form Schema Generator', 'developer', description='Generate JSON schemas for forms.', tags=['form', 'schema', 'generator', 'json', 'developer'], folder='minimal_solutions/form_schema_generator', ui_route='/minimal-solutions/form_schema_generator', api_endpoint='/api/minimal-solutions/form_schema_generator', status='Active')
registry.register('json_schema_validator_demo', 'JSON Schema Validator Demo', 'developer', description='Demo for validating JSON against a schema.', tags=['json', 'schema', 'validator', 'demo', 'developer'], folder='minimal_solutions/json_schema_validator_demo', ui_route='/minimal-solutions/json_schema_validator_demo', api_endpoint='/api/minimal-solutions/json_schema_validator_demo', status='Active')
registry.register('access_role_matrix_demo', 'Access Role Matrix Demo', 'business', description='Demo for an access role matrix.', tags=['access', 'role', 'matrix', 'demo', 'business', 'security'], folder='minimal_solutions/access_role_matrix_demo', ui_route='/minimal-solutions/access_role_matrix_demo', api_endpoint='/api/minimal-solutions/access_role_matrix_demo', status='Active')
registry.register('feature_flag_panel_demo', 'Feature Flag Panel Demo', 'developer', description='Demo for a feature flag panel.', tags=['feature', 'flag', 'panel', 'demo', 'developer'], folder='minimal_solutions/feature_flag_panel_demo', ui_route='/minimal-solutions/feature_flag_panel_demo', api_endpoint='/api/minimal-solutions/feature_flag_panel_demo', status='Active')
registry.register('theme_token_editor_demo', 'Theme Token Editor Demo', 'design', description='Demo for a theme token editor.', tags=['theme', 'token', 'editor', 'demo', 'design'], folder='minimal_solutions/theme_token_editor_demo', ui_route='/minimal-solutions/theme_token_editor_demo', api_endpoint='/api/minimal-solutions/theme_token_editor_demo', status='Active')
registry.register('language_key_editor_demo', 'Language Key Editor Demo', 'i18n', description='Demo for a language key editor.', tags=['language', 'key', 'editor', 'demo', 'i18n'], folder='minimal_solutions/language_key_editor_demo', ui_route='/minimal-solutions/language_key_editor_demo', api_endpoint='/api/minimal-solutions/language_key_editor_demo', status='Active')
registry.register('translation_missing_key_finder', 'Translation Missing Key Finder', 'i18n', description='Find missing translation keys.', tags=['translation', 'missing', 'key', 'finder', 'i18n'], folder='minimal_solutions/translation_missing_key_finder', ui_route='/minimal-solutions/translation_missing_key_finder', api_endpoint='/api/minimal-solutions/translation_missing_key_finder', status='Active')
registry.register('component_preview_card', 'Component Preview Card', 'ui_builder', description='Preview UI components.', tags=['component', 'preview', 'card', 'ui_builder'], folder='minimal_solutions/component_preview_card', ui_route='/minimal-solutions/component_preview_card', api_endpoint='/api/minimal-solutions/component_preview_card', status='Active')
registry.register('component_json_builder', 'Component JSON Builder', 'ui_builder', description='Build UI component JSON structures.', tags=['component', 'json', 'builder', 'ui_builder'], folder='minimal_solutions/component_json_builder', ui_route='/minimal-solutions/component_json_builder', api_endpoint='/api/minimal-solutions/component_json_builder', status='Active')
registry.register('html_fragment_wrapper', 'HTML Fragment Wrapper', 'ui_builder', description='Wrap HTML fragments.', tags=['html', 'fragment', 'wrapper', 'ui_builder'], folder='minimal_solutions/html_fragment_wrapper', ui_route='/minimal-solutions/html_fragment_wrapper', api_endpoint='/api/minimal-solutions/html_fragment_wrapper', status='Active')
registry.register('component_dependency_viewer', 'Component Dependency Viewer', 'ui_builder', description='View dependencies between components.', tags=['component', 'dependency', 'viewer', 'ui_builder'], folder='minimal_solutions/component_dependency_viewer', ui_route='/minimal-solutions/component_dependency_viewer', api_endpoint='/api/minimal-solutions/component_dependency_viewer', status='Active')
registry.register('iframe_preview_url_builder', 'Iframe Preview URL Builder', 'ui_builder', description='Build iframe preview URLs.', tags=['iframe', 'preview', 'url', 'builder', 'ui_builder'], folder='minimal_solutions/iframe_preview_url_builder', ui_route='/minimal-solutions/iframe_preview_url_builder', api_endpoint='/api/minimal-solutions/iframe_preview_url_builder', status='Active')
registry.register('kanban_ticket_card_generator', 'Kanban Ticket Card Generator', 'productivity', description='Generate Kanban ticket cards.', tags=['kanban', 'ticket', 'card', 'generator', 'productivity'], folder='minimal_solutions/kanban_ticket_card_generator', ui_route='/minimal-solutions/kanban_ticket_card_generator', api_endpoint='/api/minimal-solutions/kanban_ticket_card_generator', status='Active')
registry.register('task_breakdown_generator', 'Task Breakdown Generator', 'productivity', description='Break down tasks into smaller sub-tasks.', tags=['task', 'breakdown', 'generator', 'productivity'], folder='minimal_solutions/task_breakdown_generator', ui_route='/minimal-solutions/task_breakdown_generator', api_endpoint='/api/minimal-solutions/task_breakdown_generator', status='Active')
registry.register('time_estimation_calculator', 'Time Estimation Calculator', 'productivity', description='Calculate time estimations for tasks.', tags=['time', 'estimation', 'calculator', 'productivity'], folder='minimal_solutions/time_estimation_calculator', ui_route='/minimal-solutions/time_estimation_calculator', api_endpoint='/api/minimal-solutions/time_estimation_calculator', status='Active')
registry.register('daily_plan_generator', 'Daily Plan Generator', 'productivity', description='Generate a structured daily plan.', tags=['daily', 'plan', 'generator', 'productivity'], folder='minimal_solutions/daily_plan_generator', ui_route='/minimal-solutions/daily_plan_generator', api_endpoint='/api/minimal-solutions/daily_plan_generator', status='Active')
registry.register('meeting_notes_formatter', 'Meeting Notes Formatter', 'productivity', description='Format and structure meeting notes.', tags=['meeting', 'notes', 'formatter', 'productivity'], folder='minimal_solutions/meeting_notes_formatter', ui_route='/minimal-solutions/meeting_notes_formatter', api_endpoint='/api/minimal-solutions/meeting_notes_formatter', status='Active')
registry.register('decision_log_generator', 'Decision Log Generator', 'productivity', description='Generate structured decision logs.', tags=['decision', 'log', 'generator', 'productivity'], folder='minimal_solutions/decision_log_generator', ui_route='/minimal-solutions/decision_log_generator', api_endpoint='/api/minimal-solutions/decision_log_generator', status='Active')
registry.register('risk_matrix_generator', 'Risk Matrix Generator', 'business', description='Generate a risk matrix.', tags=['risk', 'matrix', 'generator', 'business'], folder='minimal_solutions/risk_matrix_generator', ui_route='/minimal-solutions/risk_matrix_generator', api_endpoint='/api/minimal-solutions/risk_matrix_generator', status='Active')
registry.register('swot_generator', 'SWOT Generator', 'business', description='Generate a SWOT analysis.', tags=['swot', 'analysis', 'generator', 'business'], folder='minimal_solutions/swot_generator', ui_route='/minimal-solutions/swot_generator', api_endpoint='/api/minimal-solutions/swot_generator', status='Active')
registry.register('pricing_table_generator', 'Pricing Table Generator', 'business', description='Generate pricing tables.', tags=['pricing', 'table', 'generator', 'business'], folder='minimal_solutions/pricing_table_generator', ui_route='/minimal-solutions/pricing_table_generator', api_endpoint='/api/minimal-solutions/pricing_table_generator', status='Active')
registry.register('feature_comparison_table', 'Feature Comparison Table', 'business', description='Generate feature comparison tables.', tags=['feature', 'comparison', 'table', 'business'], folder='minimal_solutions/feature_comparison_table', ui_route='/minimal-solutions/feature_comparison_table', api_endpoint='/api/minimal-solutions/feature_comparison_table', status='Active')
registry.register('landingpage_section_generator', 'Landingpage Section Generator', 'marketing', description='Generate landingpage sections.', tags=['landingpage', 'section', 'generator', 'marketing'], folder='minimal_solutions/landingpage_section_generator', ui_route='/minimal-solutions/landingpage_section_generator', api_endpoint='/api/minimal-solutions/landingpage_section_generator', status='Active')
registry.register('testimonial_card_generator', 'Testimonial Card Generator', 'marketing', description='Generate testimonial cards for marketing.', tags=['testimonial', 'card', 'generator', 'marketing', 'ui'], folder='minimal_solutions/testimonial_card_generator', ui_route='/minimal-solutions/testimonial_card_generator', api_endpoint='/api/minimal-solutions/testimonial_card_generator', status='Active')
registry.register('social_post_formatter', 'Social Post Formatter', 'marketing', description='Format and structure social media posts.', tags=['social', 'post', 'formatter', 'marketing'], folder='minimal_solutions/social_post_formatter', ui_route='/minimal-solutions/social_post_formatter', api_endpoint='/api/minimal-solutions/social_post_formatter', status='Active')
registry.register('hashtag_generator', 'Hashtag Generator', 'marketing', description='Generate relevant hashtags for your social media posts.', tags=['hashtag', 'generator', 'marketing', 'social'], folder='minimal_solutions/hashtag_generator', ui_route='/minimal-solutions/hashtag_generator', api_endpoint='/api/minimal-solutions/hashtag_generator', status='Active')
registry.register('youtube_description_generator', 'YouTube Description Generator', 'marketing', description='Generate engaging YouTube video descriptions.', tags=['youtube', 'description', 'generator', 'marketing', 'seo'], folder='minimal_solutions/youtube_description_generator', ui_route='/minimal-solutions/youtube_description_generator', api_endpoint='/api/minimal-solutions/youtube_description_generator', status='Active')
registry.register('tiktok_caption_generator', 'TikTok Caption Generator', 'marketing', description='Generate engaging captions for TikTok videos.', tags=['tiktok', 'caption', 'generator', 'marketing', 'social'], folder='minimal_solutions/tiktok_caption_generator', ui_route='/minimal-solutions/tiktok_caption_generator', api_endpoint='/api/minimal-solutions/tiktok_caption_generator', status='Active')
registry.register('image_prompt_generator', 'Image Prompt Generator', 'ai', description='Generate effective prompts for AI image generators.', tags=['image', 'prompt', 'generator', 'ai', 'midjourney', 'dalle'], folder='minimal_solutions/image_prompt_generator', ui_route='/minimal-solutions/image_prompt_generator', api_endpoint='/api/minimal-solutions/image_prompt_generator', status='Active')
registry.register('tts_script_generator', 'TTS Script Generator', 'ai', description='Generate scripts for Text-to-Speech (TTS) applications.', tags=['tts', 'script', 'generator', 'ai', 'speech'], folder='minimal_solutions/tts_script_generator', ui_route='/minimal-solutions/tts_script_generator', api_endpoint='/api/minimal-solutions/tts_script_generator', status='Active')
registry.register('prompt_template_builder', 'Prompt Template Builder', 'ai', description='Build and manage AI prompt templates.', tags=['prompt', 'template', 'builder', 'ai'], folder='minimal_solutions/prompt_template_builder', ui_route='/minimal-solutions/prompt_template_builder', api_endpoint='/api/minimal-solutions/prompt_template_builder', status='Active')
registry.register('ai_agent_instruction_builder', 'AI Agent Instruction Builder', 'ai', description='Build and manage instructions for AI agents.', tags=['ai', 'agent', 'instruction', 'builder'], folder='minimal_solutions/ai_agent_instruction_builder', ui_route='/minimal-solutions/ai_agent_instruction_builder', api_endpoint='/api/minimal-solutions/ai_agent_instruction_builder', status='Active')
registry.register('landingpage_generator', 'Landingpage Generator', 'marketing', description='Generate landing page layouts and structures.', tags=['landingpage', 'generator', 'marketing', 'design'], folder='minimal_solutions/landingpage_generator', ui_route='/minimal-solutions/landingpage_generator', api_endpoint='/api/minimal-solutions/landingpage_generator', status='Active')
registry.register('landingpage_formatter', 'Landingpage Formatter', 'marketing', description='Format and structure landing page content.', tags=['landingpage', 'formatter', 'marketing', 'content'], folder='minimal_solutions/landingpage_formatter', ui_route='/minimal-solutions/landingpage_formatter', api_endpoint='/api/minimal-solutions/landingpage_formatter', status='Active')
registry.register('landingpage_validator', 'Landingpage Validator', 'marketing', description='Validate landing page structures and content.', tags=['landingpage', 'validator', 'marketing', 'validation'], folder='minimal_solutions/landingpage_validator', ui_route='/minimal-solutions/landingpage_validator', api_endpoint='/api/minimal-solutions/landingpage_validator', status='Active')
registry.register('landingpage_preview', 'Landingpage Preview', 'marketing', description='Preview landing page layouts and designs.', tags=['landingpage', 'preview', 'marketing', 'design'], folder='minimal_solutions/landingpage_preview', ui_route='/minimal-solutions/landingpage_preview', api_endpoint='/api/minimal-solutions/landingpage_preview', status='Active')
registry.register('landingpage_builder', 'Landingpage Builder', 'marketing', description='Build complete landing pages.', tags=['landingpage', 'builder', 'marketing', 'design'], folder='minimal_solutions/landingpage_builder', ui_route='/minimal-solutions/landingpage_builder', api_endpoint='/api/minimal-solutions/landingpage_builder', status='Active')
registry.register('landingpage_converter', 'Landingpage Converter', 'marketing', description='Convert landing pages to different formats.', tags=['landingpage', 'converter', 'marketing', 'format'], folder='minimal_solutions/landingpage_converter', ui_route='/minimal-solutions/landingpage_converter', api_endpoint='/api/minimal-solutions/landingpage_converter', status='Active')
registry.register('landingpage_analyzer', 'Landingpage Analyzer', 'marketing', description='Analyze landing pages for SEO and performance.', tags=['landingpage', 'analyzer', 'marketing', 'seo', 'performance'], folder='minimal_solutions/landingpage_analyzer', ui_route='/minimal-solutions/landingpage_analyzer', api_endpoint='/api/minimal-solutions/landingpage_analyzer', status='Active')
registry.register('landingpage_summarizer', 'Landingpage Summarizer', 'marketing', description='Summarize landing pages and extract key points.', tags=['landingpage', 'summarizer', 'marketing', 'summary'], folder='minimal_solutions/landingpage_summarizer', ui_route='/minimal-solutions/landingpage_summarizer', api_endpoint='/api/minimal-solutions/landingpage_summarizer', status='Active')
registry.register('landingpage_checker', 'Landingpage Checker', 'marketing', description='Check landing pages for technical and content issues.', tags=['landingpage', 'checker', 'marketing', 'seo', 'quality'], folder='minimal_solutions/landingpage_checker', ui_route='/minimal-solutions/landingpage_checker', api_endpoint='/api/minimal-solutions/landingpage_checker', status='Active')
registry.register('landingpage_viewer', 'Landingpage Viewer', 'marketing', description='View and display landing pages.', tags=['landingpage', 'viewer', 'marketing', 'display'], folder='minimal_solutions/landingpage_viewer', ui_route='/minimal-solutions/landingpage_viewer', api_endpoint='/api/minimal-solutions/landingpage_viewer', status='Active')
registry.register('landingpage_exporter', 'Landingpage Exporter', 'marketing', description='Export landing pages to various formats.', tags=['landingpage', 'exporter', 'marketing', 'export'], folder='minimal_solutions/landingpage_exporter', ui_route='/minimal-solutions/landingpage_exporter', api_endpoint='/api/minimal-solutions/landingpage_exporter', status='Active')
registry.register('landingpage_importer', 'Landingpage Importer', 'marketing', description='Import landing pages from various sources.', tags=['landingpage', 'importer', 'marketing', 'import'], folder='minimal_solutions/landingpage_importer', ui_route='/minimal-solutions/landingpage_importer', api_endpoint='/api/minimal-solutions/landingpage_importer', status='Active')
registry.register('landingpage_masker', 'Landingpage Masker', 'marketing', description='Mask landing pages for specific target audiences.', tags=['landingpage', 'masker', 'marketing', 'mask'], folder='minimal_solutions/landingpage_masker', ui_route='/minimal-solutions/landingpage_masker', api_endpoint='/api/minimal-solutions/landingpage_masker', status='Active')
registry.register('landingpage_splitter', 'Landingpage Splitter', 'marketing', description='Split landing pages into multiple variations.', tags=['landingpage', 'splitter', 'marketing', 'split'], folder='minimal_solutions/landingpage_splitter', ui_route='/minimal-solutions/landingpage_splitter', api_endpoint='/api/minimal-solutions/landingpage_splitter', status='Active')
registry.register('landingpage_merger', 'Landingpage Merger', 'marketing', description='Merge multiple landing pages into one.', tags=['landingpage', 'merger', 'marketing', 'merge'], folder='minimal_solutions/landingpage_merger', ui_route='/minimal-solutions/landingpage_merger', api_endpoint='/api/minimal-solutions/landingpage_merger', status='Active')
registry.register('landingpage_cleaner', 'Landingpage Cleaner', 'marketing', description='Clean and optimize landing pages.', tags=['landingpage', 'cleaner', 'marketing', 'clean'], folder='minimal_solutions/landingpage_cleaner', ui_route='/minimal-solutions/landingpage_cleaner', api_endpoint='/api/minimal-solutions/landingpage_cleaner', status='Active')
registry.register('landingpage_normalizer', 'Landingpage Normalizer', 'marketing', description='Normalize landing page content and structures.', tags=['landingpage', 'normalizer', 'marketing', 'normalize'], folder='minimal_solutions/landingpage_normalizer', ui_route='/minimal-solutions/landingpage_normalizer', api_endpoint='/api/minimal-solutions/landingpage_normalizer', status='Active')
registry.register('landingpage_mapper', 'Landingpage Mapper', 'marketing', description='Map and structure landing pages.', tags=['landingpage', 'mapper', 'marketing', 'map'], folder='minimal_solutions/landingpage_mapper', ui_route='/minimal-solutions/landingpage_mapper', api_endpoint='/api/minimal-solutions/landingpage_mapper', status='Active')
registry.register('landingpage_diff_viewer', 'Landingpage Diff Viewer', 'marketing', description='View and analyze differences between landing pages.', tags=['landingpage', 'diff', 'viewer', 'marketing', 'compare'], folder='minimal_solutions/landingpage_diff_viewer', ui_route='/minimal-solutions/landingpage_diff_viewer', api_endpoint='/api/minimal-solutions/landingpage_diff_viewer', status='Active')
registry.register('landingpage_template_builder', 'Landingpage Template Builder', 'marketing', description='Build and customize landing page templates.', tags=['landingpage', 'template', 'builder', 'marketing', 'design'], folder='minimal_solutions/landingpage_template_builder', ui_route='/minimal-solutions/landingpage_template_builder', api_endpoint='/api/minimal-solutions/landingpage_template_builder', status='Active')
registry.register('seo_generator', 'SEO Generator', 'seo', description='Generate SEO meta tags and optimize content.', tags=['seo', 'generator', 'optimization', 'meta'], folder='minimal_solutions/seo_generator', ui_route='/minimal-solutions/seo_generator', api_endpoint='/api/minimal-solutions/seo_generator', status='Active')
registry.register('seo_formatter', 'SEO Formatter', 'seo', description='Format and structure SEO content.', tags=['seo', 'formatter', 'optimization'], folder='minimal_solutions/seo_formatter', ui_route='/minimal-solutions/seo_formatter', api_endpoint='/api/minimal-solutions/seo_formatter', status='Active')
registry.register('seo_validator', 'SEO Validator', 'seo', description='Validate SEO structures and content.', tags=['seo', 'validator', 'validation'], folder='minimal_solutions/seo_validator', ui_route='/minimal-solutions/seo_validator', api_endpoint='/api/minimal-solutions/seo_validator', status='Active')
registry.register('seo_preview', 'SEO Preview', 'seo', description='Preview SEO metadata and search engine results.', tags=['seo', 'preview', 'serp'], folder='minimal_solutions/seo_preview', ui_route='/minimal-solutions/seo_preview', api_endpoint='/api/minimal-solutions/seo_preview', status='Active')
registry.register('seo_builder', 'SEO Builder', 'seo', description='Build and optimize SEO structures.', tags=['seo', 'builder', 'optimization'], folder='minimal_solutions/seo_builder', ui_route='/minimal-solutions/seo_builder', api_endpoint='/api/minimal-solutions/seo_builder', status='Active')
registry.register('seo_converter', 'SEO Converter', 'seo', description='Convert SEO formats and content.', tags=['seo', 'converter', 'format'], folder='minimal_solutions/seo_converter', ui_route='/minimal-solutions/seo_converter', api_endpoint='/api/minimal-solutions/seo_converter', status='Active')
registry.register('seo_analyzer', 'SEO Analyzer', 'seo', description='Analyze SEO metrics and provide insights.', tags=['seo', 'analyzer', 'analysis', 'metrics'], folder='minimal_solutions/seo_analyzer', ui_route='/minimal-solutions/seo_analyzer', api_endpoint='/api/minimal-solutions/seo_analyzer', status='Active')
registry.register('seo_summarizer', 'SEO Summarizer', 'seo', description='Summarize content for SEO purposes.', tags=['seo', 'summarizer', 'content', 'summary'], folder='minimal_solutions/seo_summarizer', ui_route='/minimal-solutions/seo_summarizer', api_endpoint='/api/minimal-solutions/seo_summarizer', status='Active')
registry.register('seo_checker', 'SEO Checker', 'seo', description='Check SEO metrics and issues.', tags=['seo', 'checker', 'analysis', 'validation'], folder='minimal_solutions/seo_checker', ui_route='/minimal-solutions/seo_checker', api_endpoint='/api/minimal-solutions/seo_checker', status='Active')
registry.register('seo_viewer', 'SEO Viewer', 'seo', description='View and display SEO structures and content.', tags=['seo', 'viewer', 'display'], folder='minimal_solutions/seo_viewer', ui_route='/minimal-solutions/seo_viewer', api_endpoint='/api/minimal-solutions/seo_viewer', status='Active')
registry.register('seo_exporter', 'SEO Exporter', 'seo', description='Export SEO data and metrics to various formats.', tags=['seo', 'exporter', 'export', 'data'], folder='minimal_solutions/seo_exporter', ui_route='/minimal-solutions/seo_exporter', api_endpoint='/api/minimal-solutions/seo_exporter', status='Active')
registry.register('seo_importer', 'SEO Importer', 'seo', description='Import SEO data and metrics from various sources.', tags=['seo', 'importer', 'import', 'data'], folder='minimal_solutions/seo_importer', ui_route='/minimal-solutions/seo_importer', api_endpoint='/api/minimal-solutions/seo_importer', status='Active')
registry.register('seo_masker', 'SEO Masker', 'seo', description='Mask and format SEO content for specific audiences.', tags=['seo', 'masker', 'mask'], folder='minimal_solutions/seo_masker', ui_route='/minimal-solutions/seo_masker', api_endpoint='/api/minimal-solutions/seo_masker', status='Active')
registry.register('seo_splitter', 'SEO Splitter', 'seo', description='Split and organize SEO content and metadata.', tags=['seo', 'splitter', 'split', 'content'], folder='minimal_solutions/seo_splitter', ui_route='/minimal-solutions/seo_splitter', api_endpoint='/api/minimal-solutions/seo_splitter', status='Active')
registry.register('seo_merger', 'SEO Merger', 'seo', description='Merge and combine SEO content and metadata.', tags=['seo', 'merger', 'merge', 'content'], folder='minimal_solutions/seo_merger', ui_route='/minimal-solutions/seo_merger', api_endpoint='/api/minimal-solutions/seo_merger', status='Active')
registry.register('seo_cleaner', 'SEO Cleaner', 'seo', description='Clean and optimize SEO content and metadata.', tags=['seo', 'cleaner', 'clean', 'content'], folder='minimal_solutions/seo_cleaner', ui_route='/minimal-solutions/seo_cleaner', api_endpoint='/api/minimal-solutions/seo_cleaner', status='Active')
registry.register('seo_normalizer', 'SEO Normalizer', 'seo', description='Normalize SEO content and metadata.', tags=['seo', 'normalizer', 'normalize', 'content'], folder='minimal_solutions/seo_normalizer', ui_route='/minimal-solutions/seo_normalizer', api_endpoint='/api/minimal-solutions/seo_normalizer', status='Active')
registry.register('seo_mapper', 'SEO Mapper', 'seo', description='Map and analyze SEO content and metadata.', tags=['seo', 'mapper', 'map', 'content'], folder='minimal_solutions/seo_mapper', ui_route='/minimal-solutions/seo_mapper', api_endpoint='/api/minimal-solutions/seo_mapper', status='Active')
registry.register('seo_diff_viewer', 'SEO Diff Viewer', 'seo', description='View and analyze differences between SEO content and metadata.', tags=['seo', 'diff', 'viewer', 'compare', 'content'], folder='minimal_solutions/seo_diff_viewer', ui_route='/minimal-solutions/seo_diff_viewer', api_endpoint='/api/minimal-solutions/seo_diff_viewer', status='Active')
registry.register('seo_template_builder', 'SEO Template Builder', 'seo', description='Build and customize SEO templates.', tags=['seo', 'template', 'builder', 'marketing', 'design'], folder='minimal_solutions/seo_template_builder', ui_route='/minimal-solutions/seo_template_builder', api_endpoint='/api/minimal-solutions/seo_template_builder', status='Active')
registry.register('hosting_generator', 'Hosting Generator', 'hosting', description='Generate hosting configurations and setups.', tags=['hosting', 'generator', 'server', 'config'], folder='minimal_solutions/hosting_generator', ui_route='/minimal-solutions/hosting_generator', api_endpoint='/api/minimal-solutions/hosting_generator', status='Active')
registry.register('hosting_formatter', 'Hosting Formatter', 'hosting', description='Format and structure hosting configurations.', tags=['hosting', 'formatter', 'server', 'config'], folder='minimal_solutions/hosting_formatter', ui_route='/minimal-solutions/hosting_formatter', api_endpoint='/api/minimal-solutions/hosting_formatter', status='Active')
registry.register('hosting_validator', 'Hosting Validator', 'hosting', description='Validate hosting configurations and setups.', tags=['hosting', 'validator', 'server', 'validation'], folder='minimal_solutions/hosting_validator', ui_route='/minimal-solutions/hosting_validator', api_endpoint='/api/minimal-solutions/hosting_validator', status='Active')
registry.register('hosting_preview', 'Hosting Preview', 'hosting', description='Preview hosting environments and setups.', tags=['hosting', 'preview', 'server', 'display'], folder='minimal_solutions/hosting_preview', ui_route='/minimal-solutions/hosting_preview', api_endpoint='/api/minimal-solutions/hosting_preview', status='Active')
registry.register('hosting_builder', 'Hosting Builder', 'hosting', description='Build and optimize hosting structures.', tags=['hosting', 'builder', 'server', 'optimization'], folder='minimal_solutions/hosting_builder', ui_route='/minimal-solutions/hosting_builder', api_endpoint='/api/minimal-solutions/hosting_builder', status='Active')
registry.register('hosting_converter', 'Hosting Converter', 'hosting', description='Convert hosting configurations and setups.', tags=['hosting', 'converter', 'server', 'config'], folder='minimal_solutions/hosting_converter', ui_route='/minimal-solutions/hosting_converter', api_endpoint='/api/minimal-solutions/hosting_converter', status='Active')
registry.register('hosting_analyzer', 'Hosting Analyzer', 'hosting', description='Analyze hosting configurations and setups.', tags=['hosting', 'analyzer', 'server', 'analysis'], folder='minimal_solutions/hosting_analyzer', ui_route='/minimal-solutions/hosting_analyzer', api_endpoint='/api/minimal-solutions/hosting_analyzer', status='Active')
registry.register('hosting_summarizer', 'Hosting Summarizer', 'hosting', description='Summarize hosting configurations and setups.', tags=['hosting', 'summarizer', 'server', 'summary'], folder='minimal_solutions/hosting_summarizer', ui_route='/minimal-solutions/hosting_summarizer', api_endpoint='/api/minimal-solutions/hosting_summarizer', status='Active')
registry.register('hosting_checker', 'Hosting Checker', 'hosting', description='Check hosting configurations and metrics.', tags=['hosting', 'checker', 'server', 'check', 'monitoring'], folder='minimal_solutions/hosting_checker', ui_route='/minimal-solutions/hosting_checker', api_endpoint='/api/minimal-solutions/hosting_checker', status='Active')
registry.register('hosting_viewer', 'Hosting Viewer', 'hosting', description='View and display hosting configurations and setups.', tags=['hosting', 'viewer', 'server', 'display'], folder='minimal_solutions/hosting_viewer', ui_route='/minimal-solutions/hosting_viewer', api_endpoint='/api/minimal-solutions/hosting_viewer', status='Active')
registry.register('hosting_exporter', 'Hosting Exporter', 'hosting', description='Export hosting configurations and setups.', tags=['hosting', 'exporter', 'server', 'export'], folder='minimal_solutions/hosting_exporter', ui_route='/minimal-solutions/hosting_exporter', api_endpoint='/api/minimal-solutions/hosting_exporter', status='Active')
registry.register('hosting_importer', 'Hosting Importer', 'hosting', description='Import hosting configurations and setups.', tags=['hosting', 'importer', 'server', 'import'], folder='minimal_solutions/hosting_importer', ui_route='/minimal-solutions/hosting_importer', api_endpoint='/api/minimal-solutions/hosting_importer', status='Active')
registry.register('hosting_masker', 'Hosting Masker', 'hosting', description='Mask and format hosting configurations for specific audiences.', tags=['hosting', 'masker', 'server', 'mask'], folder='minimal_solutions/hosting_masker', ui_route='/minimal-solutions/hosting_masker', api_endpoint='/api/minimal-solutions/hosting_masker', status='Active')
registry.register('hosting_splitter', 'Hosting Splitter', 'hosting', description='Split and organize hosting configurations and setups.', tags=['hosting', 'splitter', 'server', 'split'], folder='minimal_solutions/hosting_splitter', ui_route='/minimal-solutions/hosting_splitter', api_endpoint='/api/minimal-solutions/hosting_splitter', status='Active')
registry.register('hosting_merger', 'Hosting Merger', 'hosting', description='Merge and combine hosting configurations and setups.', tags=['hosting', 'merger', 'server', 'merge'], folder='minimal_solutions/hosting_merger', ui_route='/minimal-solutions/hosting_merger', api_endpoint='/api/minimal-solutions/hosting_merger', status='Active')
registry.register('hosting_cleaner', 'Hosting Cleaner', 'hosting', description='Clean and optimize hosting configurations and setups.', tags=['hosting', 'cleaner', 'server', 'clean'], folder='minimal_solutions/hosting_cleaner', ui_route='/minimal-solutions/hosting_cleaner', api_endpoint='/api/minimal-solutions/hosting_cleaner', status='Active')
registry.register('hosting_normalizer', 'Hosting Normalizer', 'hosting', description='Normalize hosting configurations and setups.', tags=['hosting', 'normalizer', 'server', 'normalize'], folder='minimal_solutions/hosting_normalizer', ui_route='/minimal-solutions/hosting_normalizer', api_endpoint='/api/minimal-solutions/hosting_normalizer', status='Active')
registry.register('hosting_mapper', 'Hosting Mapper', 'hosting', description='Map and analyze hosting configurations and setups.', tags=['hosting', 'mapper', 'server', 'map'], folder='minimal_solutions/hosting_mapper', ui_route='/minimal-solutions/hosting_mapper', api_endpoint='/api/minimal-solutions/hosting_mapper', status='Active')
registry.register('hosting_diff_viewer', 'Hosting Diff Viewer', 'hosting', description='View and analyze differences between hosting configurations.', tags=['hosting', 'diff', 'viewer', 'server', 'compare'], folder='minimal_solutions/hosting_diff_viewer', ui_route='/minimal-solutions/hosting_diff_viewer', api_endpoint='/api/minimal-solutions/hosting_diff_viewer', status='Active')
registry.register('hosting_template_builder', 'Hosting Template Builder', 'hosting', description='Build and customize hosting templates.', tags=['hosting', 'template', 'builder', 'server', 'design'], folder='minimal_solutions/hosting_template_builder', ui_route='/minimal-solutions/hosting_template_builder', api_endpoint='/api/minimal-solutions/hosting_template_builder', status='Active')
registry.register('minecraft_generator', 'Minecraft Generator', 'gaming', description='Generate Minecraft related configurations and setups.', tags=['minecraft', 'generator', 'gaming', 'server', 'config'], folder='minimal_solutions/minecraft_generator', ui_route='/minimal-solutions/minecraft_generator', api_endpoint='/api/minimal-solutions/minecraft_generator', status='Active')
registry.register('minecraft_formatter', 'Minecraft Formatter', 'gaming', description='Format and structure Minecraft configurations.', tags=['minecraft', 'formatter', 'gaming', 'server', 'config'], folder='minimal_solutions/minecraft_formatter', ui_route='/minimal-solutions/minecraft_formatter', api_endpoint='/api/minimal-solutions/minecraft_formatter', status='Active')
registry.register('minecraft_validator', 'Minecraft Validator', 'gaming', description='Validate Minecraft configurations and setups.', tags=['minecraft', 'validator', 'gaming', 'server', 'validation'], folder='minimal_solutions/minecraft_validator', ui_route='/minimal-solutions/minecraft_validator', api_endpoint='/api/minimal-solutions/minecraft_validator', status='Active')
registry.register('minecraft_preview', 'Minecraft Preview', 'gaming', description='Preview Minecraft configurations and setups.', tags=['minecraft', 'preview', 'gaming', 'server', 'display'], folder='minimal_solutions/minecraft_preview', ui_route='/minimal-solutions/minecraft_preview', api_endpoint='/api/minimal-solutions/minecraft_preview', status='Active')
registry.register('minecraft_builder', 'Minecraft Builder', 'gaming', description='Build and optimize Minecraft structures.', tags=['minecraft', 'builder', 'gaming', 'server', 'optimization'], folder='minimal_solutions/minecraft_builder', ui_route='/minimal-solutions/minecraft_builder', api_endpoint='/api/minimal-solutions/minecraft_builder', status='Active')
registry.register('minecraft_converter', 'Minecraft Converter', 'gaming', description='Convert Minecraft configurations and setups.', tags=['minecraft', 'converter', 'gaming', 'server', 'config'], folder='minimal_solutions/minecraft_converter', ui_route='/minimal-solutions/minecraft_converter', api_endpoint='/api/minimal-solutions/minecraft_converter', status='Active')
registry.register('minecraft_analyzer', 'Minecraft Analyzer', 'gaming', description='Analyze Minecraft configurations and metrics.', tags=['minecraft', 'analyzer', 'gaming', 'server', 'analysis'], folder='minimal_solutions/minecraft_analyzer', ui_route='/minimal-solutions/minecraft_analyzer', api_endpoint='/api/minimal-solutions/minecraft_analyzer', status='Active')
registry.register('minecraft_summarizer', 'Minecraft Summarizer', 'gaming', description='Summarize Minecraft related logs and data.', tags=['minecraft', 'summarizer', 'gaming', 'server', 'summary'], folder='minimal_solutions/minecraft_summarizer', ui_route='/minimal-solutions/minecraft_summarizer', api_endpoint='/api/minimal-solutions/minecraft_summarizer', status='Active')
